'use client';
import { useEffect,useState } from 'react';
import { FIXED_KEYS,FIXED_VERSION,FIXED_KIND_LABELS, type FixedKey,type FixedTemplates,type FixedReport,type FixedBlock } from '@/lib/attachment-fixed';
import type { QuizQuestion } from '@/lib/quiz';
import { FixedSummary,FixedPreviews,FixedFullReport } from '@/app/_components/attachment-fixed-result';
const names={anxious:'焦虑型',avoidant:'回避型',fearful:'恐惧回避型',secure:'安全型'};
async function request<T>(url:string,init?:RequestInit):Promise<T>{const res=await fetch(url,{cache:'no-store',...init});const data=await res.json() as T & {error?:string};if(!res.ok)throw new Error(data.error||'请求失败');return data;}
export default function FixedReportsPanel(){
 const [templates,setTemplates]=useState<FixedTemplates|null>(null),[qs,setQs]=useState<QuizQuestion[]>([]),[key,setKey]=useState<FixedKey>('anxious'),[error,setError]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[choices,setChoices]=useState<Record<string,number>>({}),[report,setReport]=useState<FixedReport|null>(null),[view,setView]=useState<'free'|'full'>('free');
 useEffect(()=>{Promise.all([request<{templates:FixedTemplates|null}>('/api/admin/fixed-reports'),request<{questions:QuizQuestion[]}>('/api/questions?test=attachment-style&all=1')]).then(([r,q])=>{setTemplates(r.templates);const rows=q.questions.filter(x=>x.active&&x.reportConfig?.version===FIXED_VERSION);setQs(rows);setChoices(Object.fromEntries(rows.map(x=>[x.id,0])));}).catch(e=>setError(e.message));},[]);
 function edit(field:string,value:unknown){if(!templates)return;setTemplates({...templates,profiles:{...templates.profiles,[key]:{...templates.profiles[key],[field]:value}}});setDirty(true);setStatus('');setReport(null);}
 function blockEdit(section:'risks'|'deeper',i:number,patch:Partial<FixedBlock>){if(!templates)return;edit(section,templates.profiles[key][section].map((b,j)=>i===j?{...b,...patch}:b));}
 async function save(){if(!templates)return;setBusy(true);setError('');try{const r=await request<{templates:FixedTemplates}>('/api/admin/fixed-reports',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(templates)});setTemplates(r.templates);setDirty(false);setStatus(`已保存修订 ${r.templates.revision}；之后提交的新报告生效。`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function preview(){setBusy(true);setError('');try{const r=await request<{report:FixedReport}>('/api/admin/fixed-reports/preview',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({choices,templates})});setReport(r.report);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function preset(k:FixedKey){setChoices(Object.fromEntries(qs.map(q=>[q.id,q.reportConfig?.kind==='core'?q.options.findIndex(o=>o.styleKey===k):q.options.findIndex(o=>o.fixed?.tag==='skip')])));setReport(null);}
 const p=templates?.profiles[key];
 return <><div className="admin-page-heading"><div><span className="admin-kicker">依恋固定解析 V2</span><h1>报告管理与预览</h1><p>四份固定主报告 + 按真实选择匹配的解释。提交时不调用 AI。完整解读仅在付款后返回。</p></div></div>
 {error?<p className="form-error" role="alert">{error}</p>:null}{status?<p role="status">{status}</p>:null}
 {!templates?<p>报告配置尚未载入，或新版题库还未启用。</p>:<><p className="fixed-admin-note">当前修订 {templates.revision}。修改只影响以后提交的结果，已保存与已购报告保持原样。题目和每个选项的解析在「题目管理」编辑。</p>
 <section className="admin-card fixed-admin-controls"><label>主报告类型<select value={key} onChange={e=>setKey(e.target.value as FixedKey)}>{FIXED_KEYS.map(k=><option key={k} value={k}>{names[k]}</option>)}</select></label>
 {p?<><label>类型名称（英文）<input value={p.label} onChange={e=>edit('label',e.target.value)}/></label><label>免费主标题（英文）<input value={p.headline} onChange={e=>edit('headline',e.target.value)}/></label><label>免费概述（英文）<textarea value={p.summary} onChange={e=>edit('summary',e.target.value)}/></label><p>免费证据与典型行为由用户实际选项匹配，不使用与答案不符的通用特征。</p>
 {(['risks','deeper'] as const).map(section=><div key={section}><h2>{section==='risks'?'付费 · 关系风险':'付费 · 深层模式'}</h2>{p[section].map((b,i)=><details className="fixed-admin-block" key={b.id}><summary>{i+1}. {b.title}</summary><label>章节标题<input value={b.title} onChange={e=>blockEdit(section,i,{title:e.target.value})}/></label><label>免费可见的悬念预览<textarea value={b.preview} onChange={e=>blockEdit(section,i,{preview:e.target.value})}/></label><label>付费完整正文（空行分段）<textarea rows={10} value={b.paragraphs.join('\n\n')} onChange={e=>blockEdit(section,i,{paragraphs:e.target.value.split('\n\n')})}/></label></details>)}</div>)}
 <button className="admin-primary-button" disabled={busy||!dirty} onClick={()=>void save()}>{busy?'处理中…':'保存四份报告配置'}</button></>:null}</section>
 <section className="admin-card fixed-admin-controls"><h2>模拟答案，预览实际报告</h2><p>预览使用当前报告草稿和已保存的题目，不产生用户记录、订单或邮件。</p><div>{FIXED_KEYS.map(k=><button className="admin-ghost-button" key={k} onClick={()=>preset(k)}>{names[k]}</button>)}</div><p>预设仅选择前 14 题；家庭与关系背景默认不作推断，可在下方逐题选择。</p>
 <details><summary>调整 20 题演示答案</summary><div className="fixed-preview-questions">{qs.map((q,i)=><label key={q.id}>{i+1}. {q.prompt}<small>{q.reportConfig?FIXED_KIND_LABELS[q.reportConfig.kind]:''}</small><select value={choices[q.id]??0} onChange={e=>{setChoices({...choices,[q.id]:Number(e.target.value)});setReport(null);}}>{q.options.map((o,j)=><option key={o.optionId??j} value={j}>{o.label}</option>)}</select></label>)}</div></details>
 <p>规则：前 14 题四选一，每题为所选倾向加 1 分；主要倾向至少 40%、领先第二名 2 题、覆盖 3 个情境。没有明显主倾向时显示混合结果。这是产品分流规则，不是临床标准。背景 6 题不计分。</p>
 <button className="admin-primary-button" disabled={busy||qs.length!==20} onClick={()=>void preview()}>预览当前配置</button>
 {report?<><p>状态：{report.overview.state} · 有效计分 {report.overview.validCore}/14 · 配置修订 {report.templateRevision}</p><div><button className="admin-ghost-button" onClick={()=>setView('free')}>免费结果 + 解锁前预览</button><button className="admin-ghost-button" onClick={()=>setView('full')}>完整付费解读</button></div><div className="fixed-admin-preview">{view==='full'?<FixedFullReport report={report}/>:<article className="ap-results fixed-results"><FixedSummary overview={report.overview}/><FixedPreviews overview={report.overview}/>{report.overview.state!=='insufficient'?<section className="ap-paywall"><h2>解锁关系风险与形成线索</h2><p>正式页面在这两个预览下方显示当前测试价格与付款按钮。本预览不会扣款。</p></section>:null}</article>}</div></>:null}
 </section></>}
 </>;
}