import type { Metadata } from "next";
import { LegalPage, PolicySection, SUPPORT_EMAIL } from "@/app/_components/legal-page";

export const metadata: Metadata = {
  title: "Privacy Policy — DeepPersona AI",
  description: "How DeepPersona AI collects, uses, stores, and protects personal information.",
};

export default function PrivacyPage() {
  return (
    <LegalPage eyebrow="Your data, clearly explained" intro="This policy explains what information DeepPersona AI collects, why we use it, and the choices you have." title="Privacy Policy">
      <PolicySection title="1. Who we are"><p>DeepPersona AI provides short visual self-reflection tests and personalized digital interpretations. For privacy questions or requests, contact <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.</p></PolicySection>
      <PolicySection title="2. Information we collect"><ul><li><strong>Test information:</strong> the test you open, the images or answers you choose, your result, progress, and completion time.</li><li><strong>Relationship map information:</strong> nicknames and relationship types you voluntarily add, plus the visual reflections you choose to connect to those private map entries. We ask you not to enter another person&apos;s full name, contact information, or other unnecessary personal details.</li><li><strong>Contact information:</strong> your email address and whether you separately consented to marketing emails.</li><li><strong>Device profile information:</strong> a random, non-advertising identifier used to reconnect completed tests and your Inner Map on the same device.</li><li><strong>Attribution and usage information:</strong> referral source, campaign parameters, pages or test steps viewed, interaction events, and basic technical request data needed to operate and secure the service.</li><li><strong>Purchase information:</strong> product, price, currency, transaction status, and payment-provider references when paid products launch. We do not intend to store full payment-card numbers; checkout providers process payment credentials.</li><li><strong>Support information:</strong> messages and details you send when requesting help, a refund, access, correction, or deletion.</li></ul></PolicySection>
      <PolicySection title="3. How we use information"><ul><li>Deliver the requested test, calculate results, and show your personalized interpretation.</li><li>Remember completed submissions, prevent duplicate or abusive activity, troubleshoot problems, and secure the service.</li><li>Maintain your private relationship map and show how your own experience in a connection develops over time. We do not use it to diagnose the person you name.</li><li>Understand where visitors arrive from and where they leave the test flow so we can improve the experience.</li><li>Send product updates, new tests, reflections, or relevant offers only when you have opted in. You can unsubscribe at any time.</li><li>Process purchases, provide digital products, handle refunds, maintain accounting records, and meet legal obligations.</li></ul></PolicySection>
      <PolicySection title="4. Legal bases"><p>Where applicable, we rely on your consent for optional marketing; performance of a contract or steps you request before purchase to deliver tests and paid products; legitimate interests to operate, improve, and secure the service; and legal obligations for tax, accounting, fraud prevention, or lawful requests.</p></PolicySection>
      <PolicySection title="5. Sharing and service providers"><p>We may share the minimum necessary information with infrastructure and database providers, payment processors or merchants of record, email-delivery services, security and fraud-prevention providers, professional advisers, and authorities when legally required. These providers process information for defined operational purposes. We do not sell personal information for money.</p></PolicySection>
      <PolicySection title="6. International processing"><p>Our service providers may process information in countries other than yours. Where required, we use contractual or other safeguards intended to protect transferred information.</p></PolicySection>
      <PolicySection title="7. Retention"><p>We keep test submissions and associated email records only as long as reasonably needed to deliver the service, analyze performance, maintain user preferences, and resolve disputes. Marketing records are retained until you unsubscribe or request deletion, subject to a limited suppression record so we can honor the opt-out. Transaction and accounting records may be retained for the period required by applicable law.</p></PolicySection>
      <PolicySection title="8. Your choices and rights"><p>Depending on your location, you may request access, correction, deletion, restriction, portability, or objection, and you may withdraw consent. Email <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a> from the address connected to your record. You may also unsubscribe through the link in a marketing email. We may need to verify your request.</p></PolicySection>
      <PolicySection title="9. Cookies and similar technology"><p>DeepPersona AI uses a strictly necessary, non-advertising device cookie to reconnect your completed tests and Inner Map on the same browser. We may also use necessary technology to operate administrative or security features. Referral and campaign parameters may be recorded with a test session. If optional analytics, advertising pixels, or payment-provider cookies are introduced, this policy and any required consent controls will be updated before those tools are enabled.</p></PolicySection>
      <PolicySection title="10. Security"><p>We use reasonable administrative and technical safeguards, including HTTPS in transit and access controls around administrative data. No online service can guarantee absolute security.</p></PolicySection>
      <PolicySection title="11. Children"><p>The service is not directed to children under 16. If you believe a child has submitted personal information, contact us so we can review and delete it where appropriate.</p></PolicySection>
      <PolicySection title="12. Changes"><p>We may update this policy as the service, payment setup, or legal requirements change. The revised date will appear at the top of this page. Material changes will be highlighted where reasonably possible.</p></PolicySection>
    </LegalPage>
  );
}
