import { relationshipQuestions } from "./relationship-content";
import { readingThemes } from "./relationship-reading";
import { type QuizQuestion, type QuizTest } from "./quiz";

export const ATTACHMENT_TEST_ID = "attachment-style";
export const FULL_REPORT_PRICE_CENTS = 999;

export const defaultTests: QuizTest[] = [
  {
    id: ATTACHMENT_TEST_ID,
    title: "Attachment Style Quiz",
    kicker: "Free · 20 image choices",
    description: "See how you move toward or away from closeness when a relationship feels uncertain.",
    coverAtlasPath: "/quiz/relationship-v3/q01.webp",
    accent: "#9b4f5e",
    position: 1,
    active: true,
    featured: true,
    reportPriceCents: FULL_REPORT_PRICE_CENTS,
  },
  {
    id: "emotional-needs",
    title: "Your Hidden Emotional Need",
    kicker: "Paused · Being rebuilt",
    description: "This older visual test is no longer offered. Take the free attachment quiz instead.",
    coverAtlasPath: "/quiz/rooms.png",
    accent: "#2f6653",
    position: 2,
    active: false,
    featured: false,
    reportPriceCents: FULL_REPORT_PRICE_CENTS,
  },
  {
    id: "conflict-style",
    title: "Your Conflict Instinct",
    kicker: "Paused · Being rebuilt",
    description: "This older visual test is no longer offered. Take the free attachment quiz instead.",
    coverAtlasPath: "/quiz/landscapes.png",
    accent: "#b46e43",
    position: 3,
    active: false,
    featured: false,
    reportPriceCents: FULL_REPORT_PRICE_CENTS,
  },
  {
    id: "social-energy",
    title: "Your Social Battery Type",
    kicker: "Paused · Being rebuilt",
    description: "This older visual test is no longer offered. Take the free attachment quiz instead.",
    coverAtlasPath: "/quiz/rooms.png",
    accent: "#6c5a91",
    position: 4,
    active: false,
    featured: false,
    reportPriceCents: FULL_REPORT_PRICE_CENTS,
  },
  {
    id: "love-language",
    title: "How You Feel Most Loved",
    kicker: "Paused · Being rebuilt",
    description: "This older visual test is no longer offered. Take the free attachment quiz instead.",
    coverAtlasPath: "/quiz/symbols.png",
    accent: "#b35c72",
    position: 5,
    active: false,
    featured: false,
    reportPriceCents: FULL_REPORT_PRICE_CENTS,
  },
  {
    id: "stress-reset",
    title: "How You Reset Under Stress",
    kicker: "Paused · Being rebuilt",
    description: "This older visual test is no longer offered. Take the free attachment quiz instead.",
    coverAtlasPath: "/quiz/landscapes.png",
    accent: "#39747b",
    position: 6,
    active: false,
    featured: false,
    reportPriceCents: FULL_REPORT_PRICE_CENTS,
  },
  {
    id: "boundary-style",
    title: "Your Relationship Boundary Style",
    kicker: "Paused · Being rebuilt",
    description: "This older visual test is no longer offered. Take the free attachment quiz instead.",
    coverAtlasPath: "/quiz/doors.png",
    accent: "#74533b",
    position: 7,
    active: false,
    featured: false,
    reportPriceCents: FULL_REPORT_PRICE_CENTS,
  },
  {
    id: "hidden-strength",
    title: "The Strength People Miss in You",
    kicker: "Paused · Being rebuilt",
    description: "This older visual test is no longer offered. Take the free attachment quiz instead.",
    coverAtlasPath: "/quiz/symbols.png",
    accent: "#4d628b",
    position: 8,
    active: false,
    featured: false,
    reportPriceCents: FULL_REPORT_PRICE_CENTS,
  },
];

export const defaultQuestions: QuizQuestion[] = relationshipQuestions.map(question => ({
  ...question, options: question.options.map(option => ({ ...option, projection: [readingThemes[option.readingFocus ?? '']?.watch, readingThemes[option.readingFocus ?? '']?.ask].filter(Boolean).join(' ') }))
}));

export const PUBLIC_QUESTION_IDS = new Set(defaultQuestions.map((question) => question.id));

export const RETIRED_QUESTION_IDS = [
  ...defaultTests.flatMap((test) => [1, 2, 3, 4].map((index) => `${test.id}-${index}`)),
];

export const RETIRED_QUESTION_PROMPTS = [
  "They suddenly go quiet. Which door feels most like your next move?",
  "Which room feels safest to share with someone you love?",
  "Which path best matches the pace of love you trust?",
  "Which object would you keep near when a relationship feels uncertain?",
  "Which room would give you what you need most tonight?",
  "Which door feels like relief rather than escape?",
  "Which landscape gives you the deepest sense of enough?",
  "Which object feels like the missing piece today?",
  "Which path would you take after a difficult conversation?",
  "Which door matches how you return after an argument?",
  "Which room feels best for resolving something important?",
  "Which object would guide you through disagreement?",
  "Which room would restore your social battery?",
  "Which landscape matches the social plan you would actually enjoy?",
  "Which door matches your first reaction?",
  "Which object represents your energy in a group?",
  "Which object would feel most meaningful from someone you love?",
  "Which room holds your favorite kind of closeness?",
  "Which landscape would make you feel most connected?",
  "Which welcome would make you feel most loved?",
  "Which landscape would lower your stress fastest?",
  "Which room would you choose to reset?",
  "Which object feels most useful when everything is too much?",
  "Which door feels like the reset you need?",
  "Which door best represents a healthy boundary to you?",
  "Which room would you keep interruption-free?",
  "Which landscape feels like the right amount of distance?",
  "Which object best represents how you say no?",
  "Which object seems most like the way your mind works?",
  "Which door would you be most likely to open first?",
  "Which landscape reflects the strength you bring to others?",
  "Which room makes your best qualities easiest to access?",
];
