export type BankQuestion = {
  kicker: string;
  prompt: string;
  options: [string, string, string, string];
  atlas?: "/quiz/doors.png" | "/quiz/rooms.png" | "/quiz/landscapes.png" | "/quiz/symbols.png";
};

export const questionBank: Record<string, BankQuestion[]> = {
  "attachment-style": [
    { kicker: "Trust your first response", prompt: "They suddenly go quiet. Which door feels most like your next move?", atlas: "/quiz/doors.png", options: ["Ask what changed", "Send a warm check-in", "Give them space", "Wait, then reach out"] },
    { kicker: "After the tension", prompt: "You share a home after a hard conversation. Which room do you want tonight?", atlas: "/quiz/rooms.png", options: ["The open studio", "The candlelit table", "The private library", "The rain-lit retreat"] },
    { kicker: "They said we need to talk", prompt: "Which path matches what your body does first?", atlas: "/quiz/landscapes.png", options: ["Walk toward it now", "Find a softer place to sit", "Take the steady trail first", "Wait for night to settle"] },
    { kicker: "When it feels uncertain", prompt: "Which object would you keep near?", atlas: "/quiz/symbols.png", options: ["The compass", "The growing sprout", "The journal", "The prism"] },
    { kicker: "Coming back together", prompt: "After time apart, which welcome feels safest?", atlas: "/quiz/doors.png", options: ["Come in, let's go", "I've missed you", "I already handled it", "When it feels right"] },
    { kicker: "The read receipt", prompt: "They leave you on read for six hours. What do you actually do?", options: ["Ask a direct question", "Send something warm and light", "Stay quiet and wait for their timing", "Write it, delete it, wait for the feeling"] },
    { kicker: "Need to know you matter", prompt: "You need reassurance. Your first move is to…", options: ["Name it plainly", "Ask for a little closeness", "Look for a clear plan", "Wait until it feels less raw"] },
    { kicker: "They asked for space", prompt: "They want a few days alone. You…", options: ["Set a time to reconnect", "Tell them you still care", "Agree and protect the boundary", "Say yes, then hover in the feeling"] },
    { kicker: "Closeness speeds up", prompt: "The relationship is moving faster than usual. You…", options: ["Lean in and define it", "Enjoy the warmth and stay near", "Slow it down with some structure", "Stay in, but keep an inner door"] },
    { kicker: "A change in tone", prompt: "One message sounds cooler than yesterday. You…", options: ["Ask what is going on", "Offer softness first", "Give it time unless a pattern appears", "Reread it until the meaning settles"] },
    { kicker: "Right after a fight", prompt: "The argument just ended. You first…", options: ["Reopen the issue", "Repair the warmth", "Leave and sort the facts", "Wait for the emotional truth"] },
    { kicker: "One in the morning", prompt: "You miss them and cannot sleep. You…", options: ["Send the honest message", "Send a small caring note", "Write it down and wait until morning", "Sit with the feeling and not send"] },
    { kicker: "If they pull away", prompt: "Your private assumption is usually…", options: ["Something can be fixed if we talk", "The bond needs a warm signal", "They need room; I need a return time", "The timing is wrong; wait"] },
    { kicker: "What safety feels like", prompt: "You feel safest in love when…", options: ["Problems get named quickly", "Affection stays visible", "Plans and space are clear", "The mood between you feels true"] },
    { kicker: "When you are hurt", prompt: "You usually…", options: ["Go toward the person", "Look for comfort", "Create distance until you are steady", "Wait until the feeling has a shape"] },
  ],
  "emotional-needs": [
    { kicker: "Let your mind exhale", prompt: "Which room would give you what you need most tonight?", atlas: "/quiz/rooms.png", options: ["Space to create", "A place to be held", "Quiet and order", "A world of your own"] },
    { kicker: "Follow the invitation", prompt: "Which door feels like relief rather than escape?", atlas: "/quiz/doors.png", options: ["The open red door", "The warm cottage", "The hidden ivy door", "The starlit doorway"] },
    { kicker: "First feeling only", prompt: "Which landscape gives you the deepest sense of enough?", atlas: "/quiz/landscapes.png", options: ["The open coast", "The flower meadow", "The grounded forest", "The moonlit desert"] },
    { kicker: "The missing piece", prompt: "Which object feels like what you needed today?", atlas: "/quiz/symbols.png", options: ["A compass", "A living sprout", "A blank journal", "A prism"] },
    { kicker: "A hard day ends", prompt: "Which welcome would actually restore you?", atlas: "/quiz/doors.png", options: ["Let's get out of here", "Come here", "It's already handled", "No one needs anything from you"] },
    { kicker: "Too many tabs open", prompt: "Your mind is loud. You need…", options: ["A change of scene", "Someone who gets it", "One clear next step", "A room with the door closed"] },
    { kicker: "Someone offers help", prompt: "The help that actually lands is…", options: ["An option or an outing", "Listening without fixing", "Taking a task off you", "Being left in peace"] },
    { kicker: "You snap at a small thing", prompt: "Underneath, you were probably missing…", options: ["Freedom to move", "To feel received", "A bit of control", "Uninterrupted inner space"] },
    { kicker: "A free Saturday", prompt: "The version that would fill you is…", options: ["Going somewhere new", "Time with one safe person", "Catching up and clearing space", "Hours with no plans"] },
    { kicker: "Advice vs presence", prompt: "When you are low, what helps first?", options: ["A plan you can act on", "Being understood", "A smaller, ordered problem", "Silence and no questions"] },
    { kicker: "Your body keeps the score", prompt: "Stress shows up as a need for…", options: ["Motion", "Contact", "Structure", "Withdrawal"] },
    { kicker: "You cannot name it yet", prompt: "Before you have words, you want…", options: ["To do something", "A person nearby", "To tidy one corner", "To disappear for a while"] },
    { kicker: "The sentence you wish someone knew", prompt: "The truest one is…", options: ["Don't trap me", "Don't just fix me", "Don't add chaos", "Don't make me perform"] },
    { kicker: "After you get that need", prompt: "You usually feel…", options: ["Alive again", "Softer", "Clearer", "Returned to yourself"] },
    { kicker: "If the need is ignored", prompt: "You tend to…", options: ["Push for a change", "Get quieter and sadder", "Control what you can", "Leave the room, then the week"] },
  ],
  "conflict-style": [
    { kicker: "When tension rises", prompt: "Which path would you take after a difficult conversation?", atlas: "/quiz/landscapes.png", options: ["The exposed cliff", "The gentle meadow", "The quiet forest", "The wide desert"] },
    { kicker: "How you return", prompt: "Which door matches how you come back after an argument?", atlas: "/quiz/doors.png", options: ["Open it now", "Bring warmth first", "Knock when ready", "Wait for the right moment"] },
    { kicker: "Where it can be solved", prompt: "Which room feels best for something important?", atlas: "/quiz/rooms.png", options: ["The open studio", "The shared table", "The private library", "The quiet rain room"] },
    { kicker: "What you trust in a fight", prompt: "Which object would guide you?", atlas: "/quiz/symbols.png", options: ["The compass", "The sprout", "The journal", "The prism"] },
    { kicker: "The first 10 seconds", prompt: "They raise their voice. Your body goes toward…", atlas: "/quiz/doors.png", options: ["The issue", "The relationship", "The exit", "The meaning"] },
    { kicker: "A text fight starts", prompt: "You…", options: ["Call or answer the point", "Soften and check the bond", "Pause until you can be precise", "Read between the lines first"] },
    { kicker: "They go silent mid-conflict", prompt: "You…", options: ["Name the silence", "Send a caring olive branch", "Give a clear window and wait", "Assume something unspoken is happening"] },
    { kicker: "You were wrong", prompt: "Your repair usually starts with…", options: ["A direct apology and next step", "Warmth and making up", "A precise account of what you will change", "Waiting until you mean every word"] },
    { kicker: "They were wrong", prompt: "You need…", options: ["The issue named", "The connection restored", "A fair structure going forward", "Them to see the real hurt"] },
    { kicker: "In public", prompt: "Disagreement appears in front of other people. You…", options: ["Address it anyway", "Protect the warmth and take it private", "Shut it down until later", "File the subtext for later"] },
    { kicker: "The same fight again", prompt: "Your instinct is to…", options: ["Force a decision this time", "Get back to liking each other", "Write the pattern down", "Ask what this fight is really about"] },
    { kicker: "After you cool down", prompt: "The useful thing is…", options: ["Reopening it cleanly", "A kind check-in", "A plan so it does not repeat", "The sentence that was under the anger"] },
    { kicker: "What you cannot stand", prompt: "In conflict, the worst feeling is…", options: ["Being ignored", "Being disliked in the moment", "Being flooded with no structure", "Being misunderstood"] },
    { kicker: "What repair looks like", prompt: "You believe a fight is over when…", options: ["The issue is decided", "You feel close again", "The rule is clear", "The emotional truth was said"] },
    { kicker: "If it never gets resolved", prompt: "You tend to…", options: ["Keep bringing it up", "Paper over it with care", "Build a private system around it", "Live in the unanswered question"] },
  ],
  "social-energy": [
    { kicker: "After a long week", prompt: "Which room would restore your social battery?", atlas: "/quiz/rooms.png", options: ["The creative studio", "The intimate table", "The quiet library", "The rain room"] },
    { kicker: "Choose your weekend", prompt: "Which landscape matches the social plan you would actually enjoy?", atlas: "/quiz/landscapes.png", options: ["A coastal adventure", "A picnic meadow", "A familiar forest walk", "A solo moonlit drive"] },
    { kicker: "A new invitation", prompt: "Which door matches your first reaction?", atlas: "/quiz/doors.png", options: ["Step straight in", "Ask who will be there", "Look before entering", "Choose another night"] },
    { kicker: "What you bring", prompt: "Which object represents your energy in a group?", atlas: "/quiz/symbols.png", options: ["The compass", "The sprout", "The journal", "The prism"] },
    { kicker: "The party peak", prompt: "At the loudest moment, you want…", atlas: "/quiz/rooms.png", options: ["To start something", "One real conversation", "A role or a corner", "The way out"] },
    { kicker: "Someone texts a group plan", prompt: "You…", options: ["Say yes if it sounds alive", "Go if one person you like is going", "Ask for details first", "Protect the night unless it feels special"] },
    { kicker: "You have already been 'on'", prompt: "After three hours of people, you need…", options: ["A change of activity", "A smaller, warmer pocket", "A predictable wind-down", "To leave"] },
    { kicker: "A stranger starts talking", prompt: "You…", options: ["Follow the spark", "See if it becomes real", "Keep it polite and bounded", "Stay kind and slightly elsewhere"] },
    { kicker: "The plan changes last minute", prompt: "That…", options: ["Can be fun if it moves", "Is fine if the people stay good", "Costs you energy", "Makes you want to cancel"] },
    { kicker: "Your ideal Friday", prompt: "It looks like…", options: ["Going out and seeing what happens", "Dinner with one or two people", "A known plan with an end time", "Home, low lights, no performance"] },
    { kicker: "You leave early", prompt: "The honest reason is usually…", options: ["The night stopped moving", "The real conversation ended", "The stimulation passed your limit", "You wanted yourself back"] },
    { kicker: "Being the center", prompt: "Attention on you feels…", options: ["Like fuel if you can play", "Nice from people you trust", "Safer if you have a role", "Like a costume you need to take off"] },
    { kicker: "Monday after social plans", prompt: "You feel best when Saturday was…", options: ["Novel", "Intimate", "Contained", "Mostly yours"] },
    { kicker: "A friend is hurt you declined", prompt: "You wish they knew…", options: ["I need a yes to be a real yes", "I need it to be close, not big", "I need to know the shape", "Declining is how I stay fond of you"] },
    { kicker: "What actually charges you", prompt: "Other people give you energy when…", options: ["Something is happening", "Someone is really with you", "You know your place in the room", "You can leave while you still like them"] },
  ],
  "love-language": [
    { kicker: "What lands deepest", prompt: "Which object would feel most meaningful from someone you love?", atlas: "/quiz/symbols.png", options: ["A compass for a trip", "A growing plant", "A letter in a journal", "A prism chosen for you"] },
    { kicker: "Picture being cared for", prompt: "Which room holds your favorite kind of closeness?", atlas: "/quiz/rooms.png", options: ["Making something together", "A dinner for two", "A task quietly handled", "A beautiful private ritual"] },
    { kicker: "Choose the memory", prompt: "Which landscape would make you feel most connected?", atlas: "/quiz/landscapes.png", options: ["A shared adventure", "A soft place to talk", "A dependable familiar path", "A magical surprise"] },
    { kicker: "One door opens", prompt: "Which welcome would make you feel most loved?", atlas: "/quiz/doors.png", options: ["Come, let's go", "I've missed you", "I took care of it", "I made this for us"] },
    { kicker: "A hard week", prompt: "The care that would actually reach you is…", atlas: "/quiz/rooms.png", options: ["Getting you out of the house", "Sitting with you", "Handling the life stuff", "A small thing that is clearly yours"] },
    { kicker: "They only have 20 minutes", prompt: "Best use of that time is…", options: ["Do one thing together", "Say the true thing", "Knock something off your list", "Make a small moment"] },
    { kicker: "You doubt the bond", prompt: "What would restore it fastest?", options: ["A plan for time together", "Words that are specifically about you", "Them following through", "A gesture that could only be for you"] },
    { kicker: "Public vs private", prompt: "You feel more loved when they…", options: ["Include you in their life in motion", "Speak to you like you matter", "Keep their word when no one is watching", "Leave a private mark only you would notice"] },
    { kicker: "A gift arrives", prompt: "It works if it is…", options: ["A ticket, a tool, a next adventure", "Proof they listen", "Useful in the life you actually live", "Strange and exact"] },
    { kicker: "After a fight", prompt: "Love looks like…", options: ["Coming to get you", "I'm still here", "I will not repeat that", "I see what that was really about"] },
    { kicker: "Long distance or a busy month", prompt: "You need…", options: ["Something to look forward to", "Frequent emotional contact", "Reliable check-ins", "A ritual that stays yours"] },
    { kicker: "They say I love you", prompt: "It lands when…", options: ["It comes with a next chapter", "It sounds like they know you", "It matches their behavior", "It has a private meaning"] },
    { kicker: "You try to love them back", prompt: "Your natural offering is…", options: ["Experiences", "Words and warmth", "Practical loyalty", "Details and atmosphere"] },
    { kicker: "The miss", prompt: "You feel unseen when they…", options: ["Never make plans", "Stay generic", "Drop the ball", "Give something that could be for anyone"] },
    { kicker: "The deepest yes", prompt: "I feel loved when you…", options: ["Come into my world", "See me in words", "Make my life lighter", "Make it ours on purpose"] },
  ],
  "stress-reset": [
    { kicker: "Your system knows", prompt: "Which landscape would lower your stress fastest?", atlas: "/quiz/landscapes.png", options: ["A brisk coastal walk", "A gentle meadow", "A steady forest path", "A silent moonlit desert"] },
    { kicker: "One free hour", prompt: "Which room would you choose to reset?", atlas: "/quiz/rooms.png", options: ["The active studio", "The warm table", "The ordered library", "The quiet rain room"] },
    { kicker: "The first tool", prompt: "Which object feels useful when everything is too much?", atlas: "/quiz/symbols.png", options: ["The compass", "The living sprout", "The blank journal", "The light-catching prism"] },
    { kicker: "Step out of the noise", prompt: "Which door feels like the reset you need?", atlas: "/quiz/doors.png", options: ["The bold open door", "The warm cottage", "The private ivy door", "The starlit doorway"] },
    { kicker: "Sunday night tight chest", prompt: "The move that helps is…", atlas: "/quiz/landscapes.png", options: ["Leave the house", "Text someone safe", "List tomorrow into pieces", "Lights down, no input"] },
    { kicker: "A message you dread", prompt: "Before you open it, you need…", options: ["To walk first", "A person nearby", "A minute to get orderly", "The room to yourself"] },
    { kicker: "Work piled up", prompt: "Your nervous system asks for…", options: ["A burst of motion", "A human buffer", "One closed loop", "A hard stop"] },
    { kicker: "You cannot sleep", prompt: "You reset by…", options: ["Getting up and moving", "Hearing a familiar voice", "Writing the open loops down", "Making the dark quieter"] },
    { kicker: "Someone says just relax", prompt: "What actually works is…", options: ["Doing something", "Being with someone", "Making it smaller", "Being left alone"] },
    { kicker: "After bad news", prompt: "Your body wants…", options: ["Air and movement", "A hand or a call", "Facts and a next step", "A cave"] },
    { kicker: "The overstimulation tell", prompt: "You know you are over your limit when you…", options: ["Need to go", "Need someone kind", "Need to control one thing", "Need silence immediately"] },
    { kicker: "Help that misses", prompt: "The least useful offer is…", options: ["Sit still and talk longer", "Advice without company", "More emotion with no plan", "Company when you need empty space"] },
    { kicker: "20 minutes, no more", prompt: "Best reset…", options: ["Walk or change rooms", "Voice note a safe person", "Clear one surface or one task", "No phone, no talk"] },
    { kicker: "You come back to people", prompt: "You are ready when…", options: ["The charge has moved", "You feel accompanied again", "The problem has an edge", "The inner weather has changed"] },
    { kicker: "If you skip the reset", prompt: "You usually…", options: ["Get restless and sharp", "Get clingy or collapsed", "Get rigid", "Disappear"] },
  ],
  "boundary-style": [
    { kicker: "Protect your energy", prompt: "Which door best represents a healthy boundary to you?", atlas: "/quiz/doors.png", options: ["Clearly open or closed", "Warm but intentional", "Private and protected", "Open when it feels right"] },
    { kicker: "Your time is yours", prompt: "Which room would you keep interruption-free?", atlas: "/quiz/rooms.png", options: ["The working studio", "The intimate table", "The private library", "The quiet retreat"] },
    { kicker: "The right distance", prompt: "Which landscape feels like enough space?", atlas: "/quiz/landscapes.png", options: ["A clear horizon", "A nearby meadow", "A sheltered forest", "A wide open desert"] },
    { kicker: "How you say no", prompt: "Which object best represents it?", atlas: "/quiz/symbols.png", options: ["The compass", "The sprout", "The written page", "The prism"] },
    { kicker: "A last-minute ask", prompt: "Someone wants your evening. You…", atlas: "/quiz/doors.png", options: ["Give a clean yes or no", "Soften the no if you decline", "Check the existing rule first", "See if the moment actually has room"] },
    { kicker: "They keep pushing", prompt: "After the second ask, you…", options: ["Repeat the no, shorter", "Explain you still care", "Point to the boundary you already set", "Go quiet until the pressure passes"] },
    { kicker: "Family group chat", prompt: "A request crosses a line. You…", options: ["Name the line in the chat", "Take it to a kinder private message", "Mute, delay, answer on your terms", "Answer only when it feels emotionally okay"] },
    { kicker: "Work after hours", prompt: "Your honest pattern is…", options: ["A visible off switch", "A warm delay", "A rule you try to keep", "Availability that depends on the day"] },
    { kicker: "Someone reads your mood", prompt: "You want them to…", options: ["Ask straight", "Stay close but not pry", "Respect the closed door", "Wait until you open"] },
    { kicker: "Lending money, time, or a room", prompt: "You say yes when…", options: ["The terms are explicit", "The relationship can hold a no later", "The conditions are written in your head", "It feels right in this exact week"] },
    { kicker: "You already over-gave", prompt: "The correction looks like…", options: ["A blunt stop", "A kind downgrade", "A new standing rule", "A disappearing week"] },
    { kicker: "Privacy", prompt: "The thing you protect hardest is…", options: ["Your right to a direct no", "The relationship around the no", "Access to your time and inner room", "The freedom to change your mind"] },
    { kicker: "A partner wants more access", prompt: "You feel safest if…", options: ["The ask is named and decided", "They want you, not just the access", "There is a predictable rhythm", "You can open on your own timing"] },
    { kicker: "Guilt after a no", prompt: "You tell yourself…", options: ["Clear is kind", "I can be warm and still refuse", "The rule protects both of us", "I will know if I need to reopen it"] },
    { kicker: "The boundary that lasts", prompt: "It works when it is…", options: ["Obvious", "Human", "Consistent", "Alive to context"] },
  ],
  "hidden-strength": [
    { kicker: "What feels natural", prompt: "Which object seems most like the way your mind works?", atlas: "/quiz/symbols.png", options: ["The compass", "The sprout", "The journal", "The prism"] },
    { kicker: "The first door", prompt: "Which door would you open first?", atlas: "/quiz/doors.png", options: ["The bold red door", "The welcoming cottage", "The storied ivy door", "The impossible starlit door"] },
    { kicker: "The strength you bring", prompt: "Which landscape reflects what you give other people?", atlas: "/quiz/landscapes.png", options: ["The daring coast", "The generous meadow", "The grounded forest", "The visionary desert"] },
    { kicker: "Where you come alive", prompt: "Which room makes your best qualities easiest to access?", atlas: "/quiz/rooms.png", options: ["The active studio", "The gathering table", "The thoughtful library", "The imaginative rain room"] },
    { kicker: "A stuck group", prompt: "Without trying, you tend to…", atlas: "/quiz/doors.png", options: ["Start something", "Make people feel possible", "Find a workable structure", "Name the thing no one is saying"] },
    { kicker: "Friends describe you", prompt: "The compliment you half-dismiss is…", options: ["You just go", "You really see people", "You make it make sense", "You find the hidden layer"] },
    { kicker: "A messy problem", prompt: "Your first useful move is…", options: ["Try a path", "Ask who is hurting", "Map it", "Sit with the contradiction"] },
    { kicker: "Underestimated at work", prompt: "They miss that you…", options: ["Create motion before the brief is perfect", "Hold the human field", "Keep the thing from falling apart", "Catch the second meaning"] },
    { kicker: "In a crisis", prompt: "You quietly become the person who…", options: ["Goes first", "Steadies people", "Makes a plan", "Reads what is actually happening"] },
    { kicker: "A compliment that is true", prompt: "You are unusually good at…", options: ["Beginning", "Attunement", "Continuity", "Reframing"] },
    { kicker: "When you hide it", prompt: "You hide this strength when…", options: ["You don't want to look impulsive", "You don't want to carry everyone", "You don't want to be the only adult", "You don't want to sound strange"] },
    { kicker: "People come to you for…", prompt: "Usually it is…", options: ["A kickstart", "To feel less alone", "A system", "Language for a feeling"] },
    { kicker: "The cost", prompt: "The same strength costs you…", options: ["Unfinished starts", "Emotional overload", "Invisible labor", "Overthinking"] },
    { kicker: "If you trusted it more", prompt: "You would…", options: ["Lead more first steps", "Let yourself be needed on purpose", "Claim the architect role", "Share the odd observation sooner"] },
    { kicker: "The sentence that fits", prompt: "I am the person who…", options: ["gets things moving", "makes it human", "keeps it standing", "sees what else it could mean"] },
  ],
};
