import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, PolicySection, SUPPORT_EMAIL } from "@/app/_components/legal-page";

export const metadata: Metadata = {
  title: "Refund & Delivery Policy — DeepPersona AI",
  description: "Refund eligibility, digital delivery, cancellation, and payment processing information.",
  alternates: { canonical: "/refunds" },
};

export default function RefundsPage() {
  return (
    <LegalPage eyebrow="Clear digital-product fulfillment" intro="This policy applies to new orders created under these terms. Orders created under our previous policy retain that policy. Your applicable refund terms are shown before checkout." title="Refund & Delivery Policy">
      <PolicySection title="1. One-time digital purchases"><p>DeepPersona AI, operated by NEXUS FRONTIER LLC, sells digital self-reflection reports through Stripe. Each purchase unlocks the full report for the selected test result only, not all tests or future results. Prices are shown in USD before payment. There are no subscriptions or recurring charges.</p></PolicySection>
      <PolicySection title="2. Digital delivery"><p>Paid reports are digital products. The full report opens on your saved report page after successful payment confirmation. If confirmation is still pending, use “Check payment status” on that page. We also email a private report link to the address you provided with your test. This link works across browsers and is valid for 180 days; you may request a new link at /recover while your purchase remains available. Link expiry does not itself cancel your purchase. Keep the link private, because anyone holding it can access that report. Without the email link, direct report-page access requires the original browser and its site data. If you cannot access a purchase, contact support with your purchase email and receipt or order reference so we can investigate. Reports are viewed on the website; the email contains an access link, not a PDF attachment. If an email does not arrive, check your spam folder and request a resend. Email delays do not prevent immediate on-screen access after payment confirmation. There are no physical goods, shipping fees, or return shipments.</p></PolicySection>
      <PolicySection title="3. Final sales after delivery"><p>Because full reports are digital content made available after payment, purchases are generally final once the paid report has been successfully delivered and is accessible as described. We do not offer refunds solely because you change your mind, no longer want the report, disagree with a reflective interpretation, or feel it does not describe you, provided the report matches the description shown before purchase. Completing the free test alone does not constitute delivery of a paid report.</p><p>Reports use predefined scoring and written interpretations for entertainment and self-reflection. They do not promise a clinical assessment, a scientifically validated personality finding, a specific outcome, or a particular level of personal accuracy. Please review the free summary, product description and price before purchasing.</p></PolicySection>
      <PolicySection title="4. Exceptions and refund requests"><p>The final-sale rule does not remove mandatory consumer rights. We will review requests involving:</p><ul><li>A paid report that was not delivered or remains inaccessible after reasonable troubleshooting.</li><li>Duplicate or incorrect charges.</li><li>Material differences between the report and the description shown before purchase.</li><li>Unauthorized transactions, subject to appropriate investigation.</li><li>Any refund or other remedy required by applicable law.</li></ul><p>To report a problem, email <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a> with your purchase email, order or receipt reference, purchase date and a description of the issue. Contact us promptly; this does not shorten any legal deadline. We aim to reply within three business days. Where appropriate, we may first restore access or correct the issue. If we cannot provide the purchased report or another exception requires a refund, we will issue one. We may refuse fraudulent or clearly abusive requests where the law permits.</p><p>Orders created under our previous policy retain its 14-calendar-day refund request window. <Link href="/refunds/legacy-2026-09">Read the previous policy</Link>. This change does not reduce rights promised for an existing order.</p></PolicySection>
      <PolicySection title="5. How refunds are issued"><p>Approved refunds are sent to the original payment method through the payment provider. We do not control bank processing time; funds commonly take 5–10 business days to appear after a refund is issued. Taxes and currency conversion are handled according to the payment provider’s process and applicable law. Full report access ends after a full refund.</p></PolicySection>
      <PolicySection title="6. Duplicate and unauthorized charges"><p>Please contact us promptly so we can investigate before a chargeback is filed. Reporting an unauthorized payment does not limit rights available through your bank or applicable law.</p></PolicySection>
      <PolicySection title="7. Subscriptions and cancellation"><p>Purchases are one-time payments with no automatic renewal. You can leave an unfinished checkout without completing a purchase. After a successful payment, use the refund process above to request a refund.</p></PolicySection>
      <PolicySection title="8. Changes"><p>We may update this policy when products or processes change. The version presented at checkout and any mandatory consumer rights applicable at the time of purchase will govern that transaction.</p></PolicySection>
    </LegalPage>
  );
}
